export const ARTICLE_LIST_REQUEST = 'ARTICLE_LIST_REQUEST'
export const ARTICLE_LIST_SUCCESS = 'ARTICLE_LIST_SUCCESS'
export const ARTICLE_LIST_FAIL = 'ARTICLE_LIST_FAIL'
export const ORDER_ARTICLE_BY = 'ORDER_ARTICLE_BY'
export const ARTICLE_COUNT_VIEWS = 'ARTICLE_COUNT_VIEWS'

export const ARTICLE_LIST_USER_REQUEST = 'ARTICLE_LIST_USER_REQUEST'
export const ARTICLE_LIST_USER_SUCCESS = 'ARTICLE_LIST_USER_SUCCESS'
export const ARTICLE_LIST_USER_FAIL = 'ARTICLE_LIST_USER_FAIL'

export const ARTICLE_DELETE_REQUEST = 'ARTICLE_DELETE_REQUEST'
export const ARTICLE_DELETE_SUCCESS = 'ARTICLE_DELETE_SUCCESS'
export const ARTICLE_DELETE_FAIL = 'ARTICLE_DELETE_FAIL'

export const ARTICLE_SAVE_REQUEST = 'ARTICLE_SAVE_REQUEST'
export const ARTICLE_SAVE_SUCCESS = 'ARTICLE_SAVE_SUCCESS'
export const ARTICLE_SAVE_FAIL = 'ARTICLE_SAVE_FAIL'

export const ARTICLE_DETAIL_REQUEST = 'ARTICLE_DETAIL_REQUEST'
export const ARTICLE_DETAIL_SUCCESS = 'ARTICLE_DETAIL_SUCCESS'
export const ARTICLE_DETAIL_FAIL = 'ARTICLE_DETAIL_FAIL'

export const COMMENT_LIST_REQUEST = 'COMMENT_LIST_REQUEST'
export const COMMENT_LIST_SUCCESS = 'COMMENT_LIST_SUCCESS'
export const COMMENT_LIST_FAIL = 'COMMENT_LIST_FAIL'


